In [1]:
import numpy as np
import scipy.linalg as sla

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [3]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
c = np.array([7,8,9]).reshape(1,3)

In [5]:
print('a: ',a.shape)
print('c: ',c.shape)

a:  (3,)
c:  (1, 3)


In [6]:
np.c_[a,c]

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [7]:
A = np.array([[2,3,5],[1,-1,10],[-1,1,-1]])

b = np.array([10,20,5])

In [8]:
np.linalg.matrix_rank(A)

np.int64(3)

In [9]:
np.linalg.matrix_rank(np.c_[A, b])

np.int64(3)

In [10]:
A.shape[1]

3

In [11]:
def sist_lin_diagonal(A,b): return b/A.diagonal()

In [12]:
A = np.diag([1,4,2])
b = np.array([4, 2, 2])

In [13]:
sist_lin_diagonal(A,b)

array([4. , 0.5, 1. ])

In [14]:
np.empty(3).shape

(3,)

In [15]:
np.array([]).shape

(0,)

In [23]:
def sist_lin_tri_sup(A,b):
    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1]/A[-1, -1]
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
    return x

In [20]:
A = np.array([[3,4,-5,1],[0,1,1,-2],[0,0,4,-5],[0,0,0,2]])

b = np.array([-10,-1,3,2])

In [24]:
x = sist_lin_tri_sup(A,b)

x

array([ 1., -1.,  2.,  1.])

In [25]:
A.dot(x)

array([-10.,  -1.,   3.,   2.])

In [26]:
def sist_lin_tri_inf(A,b):
    n = len(b)
    x = np.empty(n)
    x[0] = b[0]/A[0, 0]
    for i in range(1,n):
        x[i] = (b[i] - np.sum(A[i,:i]*x[:i]))/A[i,i]
    return x

In [27]:
A = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])

b = np.array([4,2,4,2])

In [28]:
x = sist_lin_tri_inf(A,b)

x

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

In [29]:
A.dot(x)

array([4., 2., 4., 2.])

In [30]:
A1 = np.array([[3,4,-5,1],[0,1,1,-2],[0,0,4,-5],[0,0,0,2]])

b1 = np.array([-10,-1,3,2])

In [31]:
sla.solve_triangular(A1,b1, lower=False)

array([ 1., -1.,  2.,  1.])

In [32]:
A2 = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])

b2 = np.array([4,2,4,2])

In [33]:
sla.solve_triangular(A2,b2, lower=True)

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])